name: Build Pre-GW Pack
on:
  schedule:
    - cron: "30 1 * * *"   # 01:30 UTC = 03:30 SAST
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - name: Generate Pre-GW
        run: python main.py pre
      - name: Upload artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: pre-pack
          path: out/
      - name: Commit outputs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add out/
          git commit -m "Auto: update Pre-GW pack" || echo "No changes"
          git push